name: Test Renovate updates
on:
  push:
    branches:
      - renovate/**
  pull_request:
    branches:
      - renovate/**
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      - run: yarn test
        env:
          CI: true
